name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER.PASSWORD }}
      run:
        docker login -u rusyasun --password-stdin ${{ env.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rusyasun/calculator-app:${{ github.sha }}

    - name: Docker Push
      run: docker push rusyasun/calculator-app:${{ github.sha }}
